webtalk_init -webtalk_dir F:/ComputerOrganization/SUSTech_CS202_Computer-Organization_proj/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/CPU_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun  1 23:32:37 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ac469ef9-a97e-47ba-abb8-7a0839515315" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "af055d75d14946949e7980ab34c1ff68" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "89" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13700K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3418 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10140_KB" -context "xsim\\usage"
webtalk_transmit -clientid 119271527 -regid "" -xml F:/ComputerOrganization/SUSTech_CS202_Computer-Organization_proj/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/CPU_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/ComputerOrganization/SUSTech_CS202_Computer-Organization_proj/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/CPU_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/ComputerOrganization/SUSTech_CS202_Computer-Organization_proj/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/CPU_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
