set_property SRC_FILE_INFO {cfile:C:/Users/15755/CPU/CPU.srcs/constrs_1/new/CPUconstaint.xdc rfile:../../../CPU.srcs/constrs_1/new/CPUconstaint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clk ]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports rst ]
